/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DayNav: typeof import('./src/components/DayNav.vue')['default']
    DaySummary: typeof import('./src/components/DaySummary.vue')['default']
    LocaleToggle: typeof import('./src/components/LocaleToggle.vue')['default']
    MacroBars: typeof import('./src/components/MacroBars.vue')['default']
    MarkdownText: typeof import('./src/components/MarkdownText.vue')['default']
    MealTable: typeof import('./src/components/MealTable.vue')['default']
    PeriodChart: typeof import('./src/components/PeriodChart.vue')['default']
    ProseA: typeof import('./src/components/prose/ProseA.vue')['default']
    ProseBlockquote: typeof import('./src/components/prose/ProseBlockquote.vue')['default']
    ProseCode: typeof import('./src/components/prose/ProseCode.vue')['default']
    ProseDel: typeof import('./src/components/prose/ProseDel.vue')['default']
    ProseEm: typeof import('./src/components/prose/ProseEm.vue')['default']
    ProseHeading: typeof import('./src/components/prose/ProseHeading.vue')['default']
    ProseHr: typeof import('./src/components/prose/ProseHr.vue')['default']
    ProseLi: typeof import('./src/components/prose/ProseLi.vue')['default']
    ProseOl: typeof import('./src/components/prose/ProseOl.vue')['default']
    ProseP: typeof import('./src/components/prose/ProseP.vue')['default']
    ProsePre: typeof import('./src/components/prose/ProsePre.vue')['default']
    ProseStrong: typeof import('./src/components/prose/ProseStrong.vue')['default']
    ProseTable: typeof import('./src/components/prose/ProseTable.vue')['default']
    ProseUl: typeof import('./src/components/prose/ProseUl.vue')['default']
    RingChart: typeof import('./src/components/RingChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsPanel: typeof import('./src/components/StatsPanel.vue')['default']
    UAccordion: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_95fa38e3192d25aff494cb1c2d893863/node_modules/@nuxt/ui/dist/runtime/components/Accordion.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_95fa38e3192d25aff494cb1c2d893863/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_95fa38e3192d25aff494cb1c2d893863/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCalendar: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_95fa38e3192d25aff494cb1c2d893863/node_modules/@nuxt/ui/dist/runtime/components/Calendar.vue')['default']
    UCard: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_95fa38e3192d25aff494cb1c2d893863/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_95fa38e3192d25aff494cb1c2d893863/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_95fa38e3192d25aff494cb1c2d893863/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UPopover: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_95fa38e3192d25aff494cb1c2d893863/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_95fa38e3192d25aff494cb1c2d893863/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USwitch: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_95fa38e3192d25aff494cb1c2d893863/node_modules/@nuxt/ui/dist/runtime/components/Switch.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@3.3.7_@babel+parse_95fa38e3192d25aff494cb1c2d893863/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    WeekTrend: typeof import('./src/components/WeekTrend.vue')['default']
  }
}
