// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package db

import (
	"context"
	"time"
)

const createEntry = `-- name: CreateEntry :one
INSERT INTO entries (meal_id, food_id, name, quantity, unit, position, kcal, carb, protein, fat)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, meal_id, food_id, name, quantity, unit, position, kcal, carb, protein, fat
`

type CreateEntryParams struct {
	MealID   int64
	FoodID   *int64
	Name     string
	Quantity float64
	Unit     string
	Position int32
	Kcal     float64
	Carb     float64
	Protein  float64
	Fat      float64
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (Entry, error) {
	row := q.db.QueryRow(ctx, createEntry,
		arg.MealID,
		arg.FoodID,
		arg.Name,
		arg.Quantity,
		arg.Unit,
		arg.Position,
		arg.Kcal,
		arg.Carb,
		arg.Protein,
		arg.Fat,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.FoodID,
		&i.Name,
		&i.Quantity,
		&i.Unit,
		&i.Position,
		&i.Kcal,
		&i.Carb,
		&i.Protein,
		&i.Fat,
	)
	return i, err
}

const deleteEntry = `-- name: DeleteEntry :exec
DELETE FROM entries AS e USING meals AS m
WHERE e.id = $1 AND e.meal_id = m.id AND m.profile_id = $2
`

type DeleteEntryParams struct {
	ID        int64
	ProfileID int64
}

func (q *Queries) DeleteEntry(ctx context.Context, arg DeleteEntryParams) error {
	_, err := q.db.Exec(ctx, deleteEntry, arg.ID, arg.ProfileID)
	return err
}

const listEntriesForDay = `-- name: ListEntriesForDay :many
SELECT e.id, e.meal_id, e.food_id, e.name, e.quantity, e.unit, e.position, e.kcal, e.carb, e.protein, e.fat FROM entries e
JOIN meals m ON m.id = e.meal_id
WHERE m.profile_id = $1 AND m.date = $2
ORDER BY e.meal_id, e.position, e.id
`

type ListEntriesForDayParams struct {
	ProfileID int64
	Date      time.Time
}

func (q *Queries) ListEntriesForDay(ctx context.Context, arg ListEntriesForDayParams) ([]Entry, error) {
	rows, err := q.db.Query(ctx, listEntriesForDay, arg.ProfileID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Entry
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.FoodID,
			&i.Name,
			&i.Quantity,
			&i.Unit,
			&i.Position,
			&i.Kcal,
			&i.Carb,
			&i.Protein,
			&i.Fat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxEntryPosition = `-- name: MaxEntryPosition :one
SELECT COALESCE(MAX(position), -1)::int AS pos FROM entries WHERE meal_id = $1
`

func (q *Queries) MaxEntryPosition(ctx context.Context, mealID int64) (int32, error) {
	row := q.db.QueryRow(ctx, maxEntryPosition, mealID)
	var pos int32
	err := row.Scan(&pos)
	return pos, err
}

const updateEntry = `-- name: UpdateEntry :exec
UPDATE entries AS e
SET name = $3, quantity = $4, unit = $5, kcal = $6, carb = $7, protein = $8, fat = $9
FROM meals AS m
WHERE e.id = $1 AND e.meal_id = m.id AND m.profile_id = $2
`

type UpdateEntryParams struct {
	ID        int64
	ProfileID int64
	Name      string
	Quantity  float64
	Unit      string
	Kcal      float64
	Carb      float64
	Protein   float64
	Fat       float64
}

func (q *Queries) UpdateEntry(ctx context.Context, arg UpdateEntryParams) error {
	_, err := q.db.Exec(ctx, updateEntry,
		arg.ID,
		arg.ProfileID,
		arg.Name,
		arg.Quantity,
		arg.Unit,
		arg.Kcal,
		arg.Carb,
		arg.Protein,
		arg.Fat,
	)
	return err
}
