// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foods.sql

package db

import (
	"context"
)

const createFood = `-- name: CreateFood :one
INSERT INTO foods (profile_id, name, note, basis_unit, basis_amount, kcal, carb, protein, fat)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, profile_id, name, note, basis_unit, basis_amount, kcal, carb, protein, fat, archived, created_at, updated_at
`

type CreateFoodParams struct {
	ProfileID   int64
	Name        string
	Note        *string
	BasisUnit   string
	BasisAmount float64
	Kcal        float64
	Carb        float64
	Protein     float64
	Fat         float64
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.ProfileID,
		arg.Name,
		arg.Note,
		arg.BasisUnit,
		arg.BasisAmount,
		arg.Kcal,
		arg.Carb,
		arg.Protein,
		arg.Fat,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Note,
		&i.BasisUnit,
		&i.BasisAmount,
		&i.Kcal,
		&i.Carb,
		&i.Protein,
		&i.Fat,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFood = `-- name: DeleteFood :exec
DELETE FROM foods WHERE id = $1 AND profile_id = $2
`

type DeleteFoodParams struct {
	ID        int64
	ProfileID int64
}

func (q *Queries) DeleteFood(ctx context.Context, arg DeleteFoodParams) error {
	_, err := q.db.Exec(ctx, deleteFood, arg.ID, arg.ProfileID)
	return err
}

const getFood = `-- name: GetFood :one
SELECT id, profile_id, name, note, basis_unit, basis_amount, kcal, carb, protein, fat, archived, created_at, updated_at FROM foods WHERE id = $1 AND profile_id = $2
`

type GetFoodParams struct {
	ID        int64
	ProfileID int64
}

func (q *Queries) GetFood(ctx context.Context, arg GetFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, getFood, arg.ID, arg.ProfileID)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.Note,
		&i.BasisUnit,
		&i.BasisAmount,
		&i.Kcal,
		&i.Carb,
		&i.Protein,
		&i.Fat,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFoods = `-- name: ListFoods :many
SELECT id, profile_id, name, note, basis_unit, basis_amount, kcal, carb, protein, fat, archived, created_at, updated_at FROM foods
WHERE profile_id = $1 AND archived = false
ORDER BY name
`

func (q *Queries) ListFoods(ctx context.Context, profileID int64) ([]Food, error) {
	rows, err := q.db.Query(ctx, listFoods, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Food
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.Note,
			&i.BasisUnit,
			&i.BasisAmount,
			&i.Kcal,
			&i.Carb,
			&i.Protein,
			&i.Fat,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
