// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: foods.sql

package db

import (
	"context"
)

const createFood = `-- name: CreateFood :one
INSERT INTO foods (profile_id, name, basis_unit, basis_amount, kcal, carb, protein, fat)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, profile_id, name, basis_unit, basis_amount, kcal, carb, protein, fat, archived, created_at, updated_at
`

type CreateFoodParams struct {
	ProfileID   int64
	Name        string
	BasisUnit   string
	BasisAmount float64
	Kcal        float64
	Carb        float64
	Protein     float64
	Fat         float64
}

func (q *Queries) CreateFood(ctx context.Context, arg CreateFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, createFood,
		arg.ProfileID,
		arg.Name,
		arg.BasisUnit,
		arg.BasisAmount,
		arg.Kcal,
		arg.Carb,
		arg.Protein,
		arg.Fat,
	)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.BasisUnit,
		&i.BasisAmount,
		&i.Kcal,
		&i.Carb,
		&i.Protein,
		&i.Fat,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFood = `-- name: DeleteFood :execrows
DELETE FROM foods WHERE id = $1 AND profile_id = $2
`

type DeleteFoodParams struct {
	ID        int64
	ProfileID int64
}

func (q *Queries) DeleteFood(ctx context.Context, arg DeleteFoodParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteFood, arg.ID, arg.ProfileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getFood = `-- name: GetFood :one
SELECT id, profile_id, name, basis_unit, basis_amount, kcal, carb, protein, fat, archived, created_at, updated_at FROM foods WHERE id = $1 AND profile_id = $2
`

type GetFoodParams struct {
	ID        int64
	ProfileID int64
}

func (q *Queries) GetFood(ctx context.Context, arg GetFoodParams) (Food, error) {
	row := q.db.QueryRow(ctx, getFood, arg.ID, arg.ProfileID)
	var i Food
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.BasisUnit,
		&i.BasisAmount,
		&i.Kcal,
		&i.Carb,
		&i.Protein,
		&i.Fat,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFoods = `-- name: ListFoods :many
SELECT id, profile_id, name, basis_unit, basis_amount, kcal, carb, protein, fat, archived, created_at, updated_at FROM foods
WHERE profile_id = $1 AND archived = false
ORDER BY name
`

func (q *Queries) ListFoods(ctx context.Context, profileID int64) ([]Food, error) {
	rows, err := q.db.Query(ctx, listFoods, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Food
	for rows.Next() {
		var i Food
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.BasisUnit,
			&i.BasisAmount,
			&i.Kcal,
			&i.Carb,
			&i.Protein,
			&i.Fat,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFood = `-- name: UpsertFood :exec
INSERT INTO foods (profile_id, name, basis_unit, basis_amount, kcal, carb, protein, fat)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (profile_id, lower(name), basis_unit) DO UPDATE
SET name         = EXCLUDED.name,
    basis_amount = EXCLUDED.basis_amount,
    kcal         = EXCLUDED.kcal,
    carb         = EXCLUDED.carb,
    protein      = EXCLUDED.protein,
    fat          = EXCLUDED.fat,
    updated_at   = now()
`

type UpsertFoodParams struct {
	ProfileID   int64
	Name        string
	BasisUnit   string
	BasisAmount float64
	Kcal        float64
	Carb        float64
	Protein     float64
	Fat         float64
}

// Remember a food, or correct what we already remembered about it. Macros are
// stored per basis_amount of basis_unit (100 g, 1 ks, ...) so any quantity can
// be scaled from them later. Last write wins: fixing a value once fixes every
// suggestion that follows.
func (q *Queries) UpsertFood(ctx context.Context, arg UpsertFoodParams) error {
	_, err := q.db.Exec(ctx, upsertFood,
		arg.ProfileID,
		arg.Name,
		arg.BasisUnit,
		arg.BasisAmount,
		arg.Kcal,
		arg.Carb,
		arg.Protein,
		arg.Fat,
	)
	return err
}
