// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meals.sql

package db

import (
	"context"
	"time"
)

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (profile_id, date, name, position, note) VALUES ($1, $2, $3, $4, $5) RETURNING id, profile_id, date, name, position, note
`

type CreateMealParams struct {
	ProfileID int64
	Date      time.Time
	Name      string
	Position  int32
	Note      *string
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createMeal,
		arg.ProfileID,
		arg.Date,
		arg.Name,
		arg.Position,
		arg.Note,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Date,
		&i.Name,
		&i.Position,
		&i.Note,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :exec
DELETE FROM meals WHERE id = $1 AND profile_id = $2
`

type DeleteMealParams struct {
	ID        int64
	ProfileID int64
}

func (q *Queries) DeleteMeal(ctx context.Context, arg DeleteMealParams) error {
	_, err := q.db.Exec(ctx, deleteMeal, arg.ID, arg.ProfileID)
	return err
}

const getMealForProfile = `-- name: GetMealForProfile :one
SELECT id, profile_id, date, name, position, note FROM meals WHERE id = $1 AND profile_id = $2
`

type GetMealForProfileParams struct {
	ID        int64
	ProfileID int64
}

func (q *Queries) GetMealForProfile(ctx context.Context, arg GetMealForProfileParams) (Meal, error) {
	row := q.db.QueryRow(ctx, getMealForProfile, arg.ID, arg.ProfileID)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Date,
		&i.Name,
		&i.Position,
		&i.Note,
	)
	return i, err
}

const listMealsForDay = `-- name: ListMealsForDay :many
SELECT id, profile_id, date, name, position, note FROM meals WHERE profile_id = $1 AND date = $2 ORDER BY position, id
`

type ListMealsForDayParams struct {
	ProfileID int64
	Date      time.Time
}

func (q *Queries) ListMealsForDay(ctx context.Context, arg ListMealsForDayParams) ([]Meal, error) {
	rows, err := q.db.Query(ctx, listMealsForDay, arg.ProfileID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Date,
			&i.Name,
			&i.Position,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxMealPosition = `-- name: MaxMealPosition :one
SELECT COALESCE(MAX(position), -1)::int AS pos FROM meals WHERE profile_id = $1 AND date = $2
`

type MaxMealPositionParams struct {
	ProfileID int64
	Date      time.Time
}

func (q *Queries) MaxMealPosition(ctx context.Context, arg MaxMealPositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, maxMealPosition, arg.ProfileID, arg.Date)
	var pos int32
	err := row.Scan(&pos)
	return pos, err
}

const updateMeal = `-- name: UpdateMeal :exec
UPDATE meals SET name = $3, note = $4 WHERE id = $1 AND profile_id = $2
`

type UpdateMealParams struct {
	ID        int64
	ProfileID int64
	Name      string
	Note      *string
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) error {
	_, err := q.db.Exec(ctx, updateMeal,
		arg.ID,
		arg.ProfileID,
		arg.Name,
		arg.Note,
	)
	return err
}
