// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Entry struct {
	ID       int64
	MealID   int64
	FoodID   *int64
	Name     string
	Quantity float64
	Unit     string
	Position int32
	Kcal     float64
	Carb     float64
	Protein  float64
	Fat      float64
}

type Food struct {
	ID          int64
	ProfileID   int64
	Name        string
	BasisUnit   string
	BasisAmount float64
	Kcal        float64
	Carb        float64
	Protein     float64
	Fat         float64
	Archived    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Meal struct {
	ID        int64
	ProfileID int64
	Date      time.Time
	Name      string
	Position  int32
	Note      *string
}

type Profile struct {
	ID        int64
	UserID    string
	PublicID  string
	Name      string
	Kcal      float64
	Carb      float64
	Protein   float64
	Fat       float64
	Shared    bool
	Onboarded bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
