// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pats.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPat = `-- name: CreatePat :one
INSERT INTO personal_access_tokens (profile_id, name, token_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, profile_id, name, token_hash, scopes, created_at, last_used_at, expires_at, revoked_at
`

type CreatePatParams struct {
	ProfileID int64
	Name      string
	TokenHash string
	Scopes    []string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreatePat(ctx context.Context, arg CreatePatParams) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, createPat,
		arg.ProfileID,
		arg.Name,
		arg.TokenHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPatByHash = `-- name: GetPatByHash :one
SELECT id, profile_id, name, token_hash, scopes, created_at, last_used_at, expires_at, revoked_at FROM personal_access_tokens
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetPatByHash(ctx context.Context, tokenHash string) (PersonalAccessToken, error) {
	row := q.db.QueryRow(ctx, getPatByHash, tokenHash)
	var i PersonalAccessToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Name,
		&i.TokenHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listPats = `-- name: ListPats :many
SELECT id, profile_id, name, token_hash, scopes, created_at, last_used_at, expires_at, revoked_at FROM personal_access_tokens
WHERE profile_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPats(ctx context.Context, profileID int64) ([]PersonalAccessToken, error) {
	rows, err := q.db.Query(ctx, listPats, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalAccessToken
	for rows.Next() {
		var i PersonalAccessToken
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Name,
			&i.TokenHash,
			&i.Scopes,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePat = `-- name: RevokePat :execrows
UPDATE personal_access_tokens SET revoked_at = now()
WHERE id = $1 AND profile_id = $2 AND revoked_at IS NULL
`

type RevokePatParams struct {
	ID        int64
	ProfileID int64
}

func (q *Queries) RevokePat(ctx context.Context, arg RevokePatParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokePat, arg.ID, arg.ProfileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchPat = `-- name: TouchPat :exec
UPDATE personal_access_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchPat(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchPat, id)
	return err
}
