// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"
)

const ensureProfile = `-- name: EnsureProfile :one
INSERT INTO profiles (user_id) VALUES ($1)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, public_id, name, kcal, carb, protein, fat, shared, onboarded, created_at, updated_at
`

func (q *Queries) EnsureProfile(ctx context.Context, userID string) (Profile, error) {
	row := q.db.QueryRow(ctx, ensureProfile, userID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicID,
		&i.Name,
		&i.Kcal,
		&i.Carb,
		&i.Protein,
		&i.Fat,
		&i.Shared,
		&i.Onboarded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT id, user_id, public_id, name, kcal, carb, protein, fat, shared, onboarded, created_at, updated_at FROM profiles WHERE id = $1
`

func (q *Queries) GetProfile(ctx context.Context, id int64) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfile, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicID,
		&i.Name,
		&i.Kcal,
		&i.Carb,
		&i.Protein,
		&i.Fat,
		&i.Shared,
		&i.Onboarded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSharedProfile = `-- name: GetSharedProfile :one
SELECT id, user_id, public_id, name, kcal, carb, protein, fat, shared, onboarded, created_at, updated_at FROM profiles WHERE public_id = $1 AND shared = true
`

func (q *Queries) GetSharedProfile(ctx context.Context, publicID string) (Profile, error) {
	row := q.db.QueryRow(ctx, getSharedProfile, publicID)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicID,
		&i.Name,
		&i.Kcal,
		&i.Carb,
		&i.Protein,
		&i.Fat,
		&i.Shared,
		&i.Onboarded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profiles
SET name = $2, kcal = $3, carb = $4, protein = $5, fat = $6, shared = $7, onboarded = true, updated_at = now()
WHERE id = $1
RETURNING id, user_id, public_id, name, kcal, carb, protein, fat, shared, onboarded, created_at, updated_at
`

type UpdateProfileParams struct {
	ID      int64
	Name    string
	Kcal    float64
	Carb    float64
	Protein float64
	Fat     float64
	Shared  bool
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.ID,
		arg.Name,
		arg.Kcal,
		arg.Carb,
		arg.Protein,
		arg.Fat,
		arg.Shared,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicID,
		&i.Name,
		&i.Kcal,
		&i.Carb,
		&i.Protein,
		&i.Fat,
		&i.Shared,
		&i.Onboarded,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
