// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh.sql

package db

import (
	"context"
	"time"
)

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, family, user_agent, expires_at)
VALUES ($1, $2, COALESCE($5::text, gen_random_uuid()::text), $3, $4)
RETURNING id, user_id, token_hash, family, user_agent, expires_at, created_at, used_at, revoked_at
`

type CreateRefreshTokenParams struct {
	UserID    string
	TokenHash string
	UserAgent string
	ExpiresAt time.Time
	Family    *string
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.Family,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Family,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < now() - interval '30 days'
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, family, user_agent, expires_at, created_at, used_at, revoked_at FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Family,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE family = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshFamily(ctx context.Context, family string) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, family)
	return err
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeUserRefreshTokens, userID)
	return err
}

const useRefreshToken = `-- name: UseRefreshToken :execrows
UPDATE refresh_tokens SET used_at = now()
WHERE id = $1 AND used_at IS NULL AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) UseRefreshToken(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, useRefreshToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
