// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, email_norm, password_hash, name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, email_norm, password_hash, name, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	EmailNorm    string
	PasswordHash *string
	Name         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.EmailNorm,
		arg.PasswordHash,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNorm,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentity = `-- name: GetIdentity :one
SELECT id, user_id, provider, provider_user_id, created_at FROM identities WHERE provider = $1 AND provider_user_id = $2
`

type GetIdentityParams struct {
	Provider       string
	ProviderUserID string
}

func (q *Queries) GetIdentity(ctx context.Context, arg GetIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentity, arg.Provider, arg.ProviderUserID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, email_norm, password_hash, name, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNorm,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_norm, password_hash, name, created_at, updated_at FROM users WHERE email_norm = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, emailNorm string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, emailNorm)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNorm,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkIdentity = `-- name: LinkIdentity :one
INSERT INTO identities (user_id, provider, provider_user_id)
VALUES ($1, $2, $3)
ON CONFLICT (provider, provider_user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING id, user_id, provider, provider_user_id, created_at
`

type LinkIdentityParams struct {
	UserID         string
	Provider       string
	ProviderUserID string
}

func (q *Queries) LinkIdentity(ctx context.Context, arg LinkIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, linkIdentity, arg.UserID, arg.Provider, arg.ProviderUserID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.CreatedAt,
	)
	return i, err
}

const listIdentities = `-- name: ListIdentities :many
SELECT id, user_id, provider, provider_user_id, created_at FROM identities WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListIdentities(ctx context.Context, userID string) ([]Identity, error) {
	rows, err := q.db.Query(ctx, listIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identity
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPassword = `-- name: SetUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           string
	PasswordHash *string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	return err
}
